nav:
    - cs:
        - pl:
            - zju-c
        - algo:
            - zju-fds:
                - chapter-01
        - blockchain:
            - 3b1b
            - zju-bc
    - sci:
        - la:
            - chapter-01
            - chapter-02
            - chapter-03
            - chapter-04
            - chapter-05
            - chapter-06
            - chapter-07
            - chapter-08
        - am:
            - lagrange
    - music:
        - harmony:
            - funda:
                - chapter-01
        - intonation:
            - chapter-01
            - chapter-02
            - chapter-03
    - misc:
        - test:
            - customToken
            - latex
            - markdown

icon:
    cs: code
    sci: atom
    misc: box-archive
    music: music