nav:
    - cs:
        - pl:
            - zju-c
        - algo:
            - zju-fds:
                - chapter-01
        - blockchain:
            - 3b1b
            - zju-bc
    - sci:
        - la:
            - zju-la
    - music:
        - harmony:
            - funda:
                - chapter-01
    - misc:
        - test:
            - customToken
            - latex
            - markdown

icon:
    cs: code
    sci: atom
    misc: box-archive
    music: music