name: Build and Deploy to Vercel

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout App Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  submodules: true

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install Dependencies in app and plugin
              run: npm ci

            - name: Generate Cache
              run: npm run cache

            - name: Build Project
              run: npm run build

            - name: Copy vercel.json
              run: cp vercel.json ./dist

            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v25
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  working-directory: ./dist
                  vercel-args: "--prod"
